### ISSUE TITLE
[Suggestion] Pause presence if RA status hasn’t changed for more then a specified amount of time

### ISSUE THREAD

**Issue by solitonmedic** [sajtii/ra_cli#1]
Hello, I managed to get this running on my cloud machine, and I love how fanastic it looks.

It would be lovely if the program knew to stop sending rich presence data when my game status has not been changed for more then a set amount of time I’ve specified.

I have a few other rich presence programs so sending data and it would be helpful if this program knew when to start itself back up when it detects a change on my RA game status.

**Comment by sajtii** [comment]
Hello! Thanks

**Comment by sajtii** [comment]
Hello! Thanks for your feedback. Sure thing, as soon as I have some time, I will implement your idea with a few little tweaks to better suit this kind of use case.

**Comment by sajtii** [comment]
Done. Due to the way I wrote my code I had to do a little workaround to make this work. Use 'python racli.py -t' to set a timeout value. It will work together with your interval value. For example, if the interval is set to 30 seconds and the timeout to 6, this means after 6 cycles of 30 seconds each (3 minutes), if the status message remains the same, the script will stop updating the presence. After that, the script checks your status every 30 seconds (or whatever your interval value is) and if it is new, the rich presence goes live once again. Test it, and if you have any issues or ideas, I am happy to hear about them.

**Comment by solitonmedic** [comment]
Amazing! I can confirm it’s running just fine with my server.

Also, one thing to note, the`racli.py` within the git repository has a syntax error at line 364, I realized that when I reinitialized my copy of the repo.

I had to change the line to `a_game_prog = ra_game_prog.get(f"{ra_userdata['LastGameID']}", {})` for the script to work.

**Comment by sajtii** [comment]
You gave me quite a bit of confusion because, for some reason, I did not get any syntax error, and I did not notice the commas. All I saw was that you copy-pasted the exact same line, but after scratching my head for a few minutes, I noticed. Thank you so much for pointing it out, I have already fixed it.

**Comment by sajtii** [comment]
Also, I noticed a major mistake related to the timeout, so I updated the script once more. Make sure you update yours too.
